### ISSUE TITLE
Thoroughly validate Polymath format, inputs, and outputs

### ISSUE THREAD

**Issue by dglazkov** [polymath-ai/polymath-ai#33]
Here's what I am thinking:

- There is a `core/validation` package
- The package contains all logic to validate Polymath format (inputs/outputs, etc.)
- The `core/client` package depends on it and uses it

This setup seems better, because it allows validation to stay independent from the client, and centralizes all logic that ensures integrity of the format.

Some of the things that we need to validate:

- is a given input (a Polymath query) valid?
- is a given output (a Polymath response) valid?
- is a given file (a Polymath library) valid?

**Comment by dalmaer** [comment]
+1 to having its own package. And we can have a library package that is akin to py library-ish... that validation can use later, and client etc can use too.

For the library we can maybe abstract: library can contain multiple files which each have bits, the notion of results from querying a library, etc.

**Comment by dglazkov** [comment]
I will declare provisional victory on this one.
