### ISSUE TITLE
application/json; charset=utf-8 means request/validation will fail.

### ISSUE THREAD

**Issue by PaulKinlan** [polymath-ai/polymath-ai#55]
If the server returns some extra metadata on the content type (such as charset) then the request will fail.

This extra meta-data is valid (imo).

**Comment by PaulKinlan** [comment]
Some context: I can't get vercel to not return the charset. :(

**Comment by dglazkov** [comment]
I think that's fine. Seems like a good thing for polymath to know the charsets.

**Comment by PaulKinlan** [comment]
Fix incomming.

**Comment by dalmaer** [comment]
+1 we accept all the things! :)

**Comment by dglazkov** [comment]
https://www.npmjs.com/package/content-type-parser by Domenic!

**Comment by PaulKinlan** [comment]
There's an argument for a custom `application/json+polymath` - Activity Pub does something similar (can be discussed later though :D)

**Comment by PaulKinlan** [comment]
Oh https://www.npmjs.com/package/content-type-parser is neat, I was just using a regex. Let's use https://www.npmjs.com/package/content-type-parser and we can be generally more robust in the future.

**Comment by dglazkov** [comment]
🦾  zero dependencies, too!
