### ISSUE TITLE
Create `core/host`

### ISSUE THREAD

**Issue by dglazkov** [polymath-ai/polymath-ai#58]
We need a package to easily build Polymath hosts. Currently, `core/client` does a bit of the job, but it doesn't appear to provide an actual code for hosting a Polymath instance.

**Comment by dalmaer** [comment]
What is the difference between host and remix for example?

I sometimes struggle with where the endpoint host ends and the client begins, as in practice you pull on the thread and ... "so the host should have a way to query it.., oh and the endpoint can act as a mixer and chain...."

Remix acts as a client and an endpoint host.... and gains powers such as streaming.

Then there is single vs. multi tenant which are different packages. Remix is single now, but another package will allow for one instance to support multiple Polymaths (supabase config etc).

I think we want to nudge on:

- Easy to setup a Polymath
- Get value quickly from doing so (Eg ingest!, /admin ability to just add and manage content, map to others, have a nice client, ...)
- Hard to setup without having a valid endpoint that can plugin to the borg

I have come to see `client` as "a library that can be used to talk to and be a polymath" but doesn't have the "I can listen via HTTP" or "I speak UI" layers. This allows for a lot of reuse between a Remix impl and any other web impl... or React Native! ;)

**Comment by dglazkov** [comment]
Here's how I see the separation:

Host:
- knows nothing about OpenAI or any other generative AI APIs.
- knows how to load libraries from Pinecone or locally
- has one API: take a bag of form data (with the base64-encoded embedding + params) and return `LibraryData` 

Client:
- knows nothing about loading libraries
- has knowledge of the OpenAI stuff and supports various cool mixing and chaining capabilities
- knows how to take a string and turn it into an embedding and call host
- knows how to take host's output and feed into the mixers, chains, etc.

Does that make sense?

**Comment by dglazkov** [comment]
The basic idea is that host is just about hosting and serving a library, nothing else.

How Remix kit fits into it:

- Remix kit depends on client to provide frontend for remix and chaining capabilities
- (underneath, client calls to host via HTTP or depends on host API directly)
- Remix kit depends on host to provide an HTTP endpoint.

**Comment by dalmaer** [comment]
Ok, so I rewrite what you are saying...:

- have a strong separation between Client and Host as you mention with the packages
- kits end up the glue that make the pragmatic "but I just want a thing and I want it to work and not have to setup multiple things etc" E.g. Remix kit does this using Remix, but ofc we have others... but they should be just wiring up the client and host packages.

Would it be nice to have a lil separation in host, where it can:

- Act just as a library, so Remix kit handles the http stuff, and uses the library. So, `/endpoint/ask` ends up being something like:

```js
// uses the client, grabs from config
import { PolymathHost } from "~/utils/polymath.host";

export async function action({ request }: ActionArgs) {
  // get the info from the formdata, or even better also offer...
  let results = host.ask(request);
  return json(results);
}

- Host has a simple way to deploy itself (with adapters) as just a host.

**Comment by dglazkov** [comment]
Yes! It's similar in spirit to what we do in `core/cli` -- it only wires stuff up, but tries to avoid having load-bearing logic.

**Comment by dglazkov** [comment]
`core/cli` is the original kit 😆

**Comment by dalmaer** [comment]
yup, yup. and with this, it's trivial to make more kits for different web frameworks and hosts.

**Comment by dalmaer** [comment]
(I see an excalidraw diagram to show how our bits fit together for folks in the future)
