### ISSUE TITLE
chore: TypeScript. For Alex. And others.

### ISSUE THREAD

**Issue by dalmaer** [polymath-ai/polymath-ai#9]
Switch over to TypeScript!

**Comment by jkomoros** [comment]
Please god

**Comment by dglazkov** [comment]
I am going to tackle this next

**Comment by dglazkov** [comment]
Here's what I am thinking: we will go with an explicit build step.

All of our packages are published in JS, not TS. Similar to this: 
https://www.npmjs.com/package/@turbo/workspaces?activeTab=explore

Probably using https://github.com/egoist/tsup

**Comment by dglazkov** [comment]
Here's what I am thinking so far:

✅ we're doing an explicit build step, all packages are published in JS.
✅  we have a convention for `./dist` directory where the outputs are done.
❓  do we use `tsup` to bundle the package before publishing?

**Comment by dglazkov** [comment]
- [x] build typescript at all
- [x] make it link binaries without extra fuss
- [x] get it as close to just omitting types as possible
- [x] make it run with tests
- [x] make it properly publishable
- [x] implement `-w` workflow
- [x] make it quickly buildable, separately and together.

**Comment by dglazkov** [comment]
Two items remaining -- a proper watch support and test publishing. I think both are fairly straightforward, but I am guessing publishing will need some serious testing to get right.

**Comment by dglazkov** [comment]
Declaring victory.
